#
# Module manifest for module 'JhcAdoRest'
#
# Generated by: jcravener@hotmail.com
#
# Generated on: 11/9/2021
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'JhcAdoRest.psm1'

# Version number of this module.
ModuleVersion = '1.1.4'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '155557b1-319e-4021-9746-f7fa105ad170'

# Author of this module
Author = 'jcravener@hotmail.com'

# Company or vendor of this module
CompanyName = 'jcravener@hotmail.com'

# Copyright statement for this module
Copyright = 'jcravener@hotmail.com'

# Description of the functionality provided by this module
Description = 'Collection of Cmdlets that run Azure Dev Ops Rest API calls. Provides access to Build definitions, specific Builds and Build Timelines.; Release definitions and specific releases; Pipelines and pipeline runs; Full YAML Pipeline definition payloads; Agent Pools; Agent Pool Queues; Pull requests.  The Select-* cmdlets transforms raw JSON response payloads into useful report objects.'

# Minimum version of the PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @('setenv.ps1') # removing this in v1.1 becuse command-completion hangs when you try to use a cmdlet before this script runs.  Instead, v1.0.4 users should use Set-JhcAdoRestEnvironment cmdlet

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'Get-JhcAdoRestEnvironment',
    'Set-JhcAdoRestEnvironment',
    'Invoke-JhcAdoRestPipelinePreviewRun',
    'Invoke-JhcAdoRestBuildDefinition',
    'Invoke-JhcAdoRestBuildList',
    'Invoke-JhcAdoRestPipeline',
    'Invoke-JhcAdoRestPipelineRuns',
    'Invoke-JhcAdoRestBuild',
    'Invoke-JhcAdoRestBuildTimeline',
    'Invoke-JhcAdoRestGitPullRequest',
    'Invoke-JhcAdoRestReleaseDefinition',
    'Invoke-JhcAdoRestRelease',
    'Select-JhcAdoRestAgentQueue',
    'Select-JhcAdoRestAgentPool',
    'Select-JhcAdoRestBuildDefinition',
    'Select-JhcAdoRestBuild',
    'Select-JhcAdoRestReleaseDefinition',
    'Select-JhcAdoRestRelease',
    'Invoke-JhcAdoRestAgentPool',
    'Invoke-JhcAdoRestAgentQueue'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

